---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: mcr.microsoft.com/azure-storage/azurite
          ports:
            - containerPort: {{ .Values.azurite_port }}
          command: {{.Values.azurite_component }}
          args: {{ .Values.azurite_arguments }}
          securityContext:
            runAsUser: 0
