apiVersion: v1
kind: Service
metadata:
  name: {{ template "hello_azure.name" }}
  labels:
    app: {{ template "hello_azure.name" }}
spec:
  ports:
    - port: 80
      protocol: TCP
    selector:
      app: {{ template "hello_azure.name" }}
