---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-webserver
          image: {{ .Values.app.imageName }}
          ports:
            - containerPort: 5000
          command:
            - python
          args:
            - hello_azure.py
          env:
            {{- range $key, $val := .Values.app.environment_secrets }}
            name: {{ $key | upper }}
            valueFrom:
              secretKeyRef:
                key: {{ $key }}
                name: {{ .Release.Name }}-secrets
            {{- end }}
