---
{{- $chartName := .Chart.Name }}
{{- $releaseName := .Release.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $chartName }}
  labels:
    app: {{ $chartName }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
    spec:
      containers:
        - name: {{ $chartName }}-webserver
          image: {{ .Values.app.imageName }}
          ports:
            - containerPort: 5000
          command:
            - python
          args:
            - hello_azure.py
          env:
            - name: LOG_LEVEL
              value: {{ .Values.app.log_level }}
            - name: SESSION_DB_HOST
              value: {{ .Values.app.session_db_host }}
            - name: SESSION_DB_PORT
              value: "{{ .Values.app.session_db_port }}"
            - name: FLASK_HOST
              value: {{ .Values.app.flask_host }}
            - name: FLASK_PORT
              value: "{{ .Values.app.flask_port }}"
            {{- range $key, $val := .Values.app.environment_secrets }}
            - name: {{ $val }}
              valueFrom:
                secretKeyRef:
                  key: {{ $val }}
                  name: {{ $releaseName }}-secrets
            {{- end }}
