---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  {{- range .Files.Lines "environment_file" }}
  {{- $key := regexReplaceAll "^([A-Z0-9_]+)=" . "$1" }}
  {{- $value := replace (printf "%s=" $key) "" }}
  {{ $key }}: {{ $value }}
  {{- end }}
