{{- range .Files.Lines ".env.test" }}
{{- $key := regexReplaceAll "^([A-Z0-9_]+)=" . "$1" }}
{{- $value := replace (printf "%s=" $key) "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{- printf "%s-secret" (lower $key) }}
type: Opaque
data:
  value: {{- $key }}
{{- end }}
