---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  {{- range .Files.Lines "environment_file" -}}
  {{- if (ne . "") }}
  {{- $line := . | default "foo" }}
  {{- $key := regexReplaceAll "^(.*?)=(.*)$" $line "$1" }}
  {{- $value := $line | replace (printf "%s=" $key) "" }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end -}}
  {{- end -}}
