app:
  replicaCount: 1
  imageName: 10.0.2.2:5000/hello-azure
  environment_secrets:
    - FLASK_HOST
    - FLASK_PORT
    - SESSION_DB_HOST
    - SESSION_DB_PORT
    - SESSION_DB_USER
    - SESSION_DB_PASSWORD
