#!/usr/bin/env bash
#vim: set ft=sh:

provision_local_k3s_cluster_and_registry() {
}

build_docker_image() {
}

push_into_private_registry() {
}

deploy_helm_chart() {
}

if ! provision_local_k3s_cluster_and_registry &&
  build_docker_image &&
  push_into_private_registry &&
  deploy_helm_chart
then
  >&2 echo "🚨 ERROR: Failed to deploy; see logs."
  exit 1
fi
